"""
map_walls.py

Parses the static wall geometry (boundary + interior maze walls) out of
a real MuJoCo map XML generated by mujoco_map_gen.py / generate_map_batch.py,
WITHOUT needing MuJoCo itself -- just reads the XML.

Deliberately excludes pedestrians: they have freejoint bodies (dynamic,
physics-driven), which our pure-PyTorch differentiable pipeline doesn't
simulate. Only static wall geometry is used.
"""

import xml.etree.ElementTree as ET

import torch


def load_walls(xml_path):
    """
    Returns a (K, 4) tensor of [cx, cy, half_x, half_y] for every
    boundary_* and wall_* geom in the map (all axis-aligned rectangles).
    """
    tree = ET.parse(xml_path)
    root = tree.getroot()

    walls = []
    for geom in root.iter("geom"):
        name = geom.get("name", "")
        if name.startswith("boundary_") or name.startswith("wall_"):
            pos = geom.get("pos").split()
            size = geom.get("size").split()
            cx, cy = float(pos[0]), float(pos[1])
            hx, hy = float(size[0]), float(size[1])
            walls.append([cx, cy, hx, hy])

    if not walls:
        raise ValueError(f"No wall geoms found in {xml_path}")

    return torch.tensor(walls)
